module.exports = {
  DATABASE_NAME: process.env.CLEARDB_DATABASE_NAME,
  DATABASE_URL: process.env.CLEARDB_DATABASE_URL,
  DATABASE_USERNAME: process.env.CLEARDB_DATABASE_USERNAME,
  DATABASE_PASSWORD: process.env.CLEARDB_DATABASE_PASSWORD
};
